###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = nemo
$menu = rofi -show drun
$codeEditor = code
$browser = librewolf
$passwordManager = keepassxc
$wallpaperScript = $DOTFILES/script/wallpaper.sh

#################
### AUTOSTART ###
#################

exec-once = swww-daemon
exec-once = $HOME/wallpaper.sh random
exec-once = waybar &
exec-once = nm-applet &
exec-once = hyprctl setcursor Bibata-Modern-Ice 24

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = DOTFILES, $HOME/.dotfiles
env = DEFAULT_WAL_CONTRAST, 2.5
env = DEFAULT_WAL_SATURATE, 0.5
env = QT_STYLE_OVERRIDE,kvantum
env = QT_QPA_PLATFORM, wayland


##############
### IMPORT ###
##############

source = $HOME/.cache/wal/custom-hyprland-colors.conf
source = $HOME/.config/hypr/input.conf
source = $HOME/.config/hypr/keybinds.conf
source = $HOME/.config/hypr/style.conf
source = $HOME/.config/hypr/windowrules.conf
source = $HOME/.config/hypr/monitor.conf
